language: node_js
node_js:
  - "12.3.0"

branches:
only:
  - master

before_script:
  - npm install

script:
  - npm run test

notifications:
  email:
    recipients:
      - lariel.negreiros@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
